name: Build Godot 
on:
    push:
    pull_request:
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: paulloz/godot-action@v1.2.2
              with:
                version: 4.0
    buildLinux:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - run: |
                godot --version
                godot --export linux .
            - run: |
                ls -la
            - uses: actions/upload-artifact@v2
              with:
                name: linux
                path: export/linux
    buildWindows:
        runs-on: windows-latest
        needs: setup
        steps:
            - run: |
                godot --version
                godot --export windows ./windows
            - run: |
                ls -la
            - uses: actions/upload-artifact@v2
              with:
                name: windows
                path: export/windows
    runTests:
        runs-on: ubuntu-latest
        needs: buildLinux
        steps:
            - run: |
                ls -la
